import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SidebarNav from "@/components/Sidebar";
import { Provider } from "react-redux";
import store from "@/redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
        <body className={cn(inter.className, "flex w-full")}>
          <div>
            <SidebarNav />
          </div>
          <div className="p-8 w-full">{children}</div>
        </body>
    </html>
  );
}
